config/routes.rb
Rails.application.routes.draw do

  root 'users#home'
  resources :users, only: [:new, :create, :show, :edit, :update]
  resource :sessions, only: [:create, :destroy]
  resources :auctions, only: [:index, :new, :destroy, :create, :show]
  resources :bids, only: [:create, :destroy]
  resources :dashboards, only: [:index]
  resources :addresses, only: [:create, :update]

  post "users/subscribe" => "users#subscribe"

end

app/models/address.rb
class Address < ActiveRecord::Base
  has_many :deliveries
  has_many :auctions

  belongs_to :user

  validates :street, :city, :zip_code, presence: true
  validates :state, length: { maximum: 2 }

  before_save :upcase_state

  private
  def upcase_state
    self.state.upcase!
  end

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  belongs_to :address
  belongs_to :user

  has_one :delivery
  has_many :bids

  validates :title, :description, presence: true, length: { minimum: 2}
  validates :minimum_price, numericality: {greater_than_or_equal_to: 1}, presence: true

  before_save :add_default_status
  before_save :add_default_auction_end

  private
   def add_default_status
     self.status = "New"
   end
   def add_default_auction_end
     self.auction_end = Time.now
   end
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :auction

  validates :price, presence: true, numericality: true

  validate :bid_must_be_lower


  private
    def bid_must_be_lower
      if Bid.find_by(auction_id: self.auction.id)
        current_lowest_bid = Bid.where(auction_id: self.auction.id).last.price
      else
        current_lowest_bid = Auction.find(self.auction.id).minimum_price
      end

      if self.price >= current_lowest_bid
        errors.add(:bid_price, "cannot be higher than the current bid")
      end
    end

end

app/models/delivery.rb
class Delivery < ActiveRecord::Base
  belongs_to :users
  belongs_to :address
  belongs_to :auction

  validates :price, numericality: true, presence: true
end

app/models/subscribe.rb
class Subscribe < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  belongs_to :address

  has_many :deliveries
  has_many :auctions
  has_many :bids

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :first_name, :last_name, presence: true, length: { minimum: 2 }
  validates :email, presence: true, format: { with: EMAIL_REGEX }

  before_create :user_level

  after_create :successfully_created

  #this callback will give the user a level of 1 when created.
  private
    def user_level
      self.level = 0
    end
    def successfully_created
      puts "User ID: #{self.id} created with level: #{self.level}"
    end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def create
    @user = User.find(session[:user_id])
    @address = Address.new(update_address)
    User.update(@user.id, address: @address)
    if @address.save
      redirect_to :back
    else
      flash[:errors] = @address.errors.full_messages 
      redirect_to :back
    end
  end

  def update
    @user = User.find(session[:user_id])
    @address = Address.find(@user.address_id)
      if @address.update(update_address)
        redirect_to :back
      else
        flash[:errors] = @address.errors.full_messages   
        redirect_to :back       
      end
  end
  private
    def update_address
      params.require(:address).permit(:street, :city, :state, :zip_code)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
  User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  def index
    @user = User.find(session[:user_id])
    @auctions = Auction.all.order("created_at ASC").limit(10).where(status: "New")
  end

  def new
    @user = User.find(session[:user_id])
  end
  def create
    @user = User.find(session[:user_id])
    @new_auction = Auction.new(new_auction)
    if @new_auction.save
      redirect_to '/auctions'
    else
      flash[:errors] = @new_auction.errors.full_messages
      redirect_to :back
    end
  end
  def show
    @auction_find = Auction.find(params[:id])
    @auction_history = Auction.find(params[:id]).bids.order("created_at DESC").limit(10)
    @last_bid = Auction.find(params[:id]).bids.order("created_at DESC").limit(1).select(:price).first
    @user = User.find(session[:user_id])
    @pastauctions = Auction.where.not(status:new)
    @my_auctions = Auction.where(user: current_user )
    @all_auctions = Auction.all

    # test
    geocodio = Geocodio::Client.new('07980857e0feeaa078509a098a8078e60509d99')
    results = geocodio.geocode(['175 E Olive Ave, Burbank, CA 91502'])
    @results = results.best
  end
  def edit
  end
  def update
  end

  def destroy
     Auction.find(params[:id]).delete
     redirect_to '/auctions'
  end
  private
    def new_auction
      params.require(:auction).permit(:title, :description, :minimum_price, :address_id, :user_id)
    end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  def create
    @new_bid = Bid.new(price: params[:price], user: User.find(session[:user_id]), auction: Auction.find(params[:auction_id]))
    # @last_bid = Auction.find(params[:auction_id]).bids.order("created_at DESC").limit(1).select(:price).first
    if @new_bid.save
    else
      flash[:errors] = @new_bid.errors.full_messages
    end
    redirect_to :back
  end

  def destroy
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @user = User.find(session[:user_id])
    @bids = Bid.where(user: @user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
  @user = User.find_by(email: params[:email])
  if @user && @user.authenticate(params[:password])
    session[:user_id] = @user.id
    redirect_to "/auctions"
  else
    flash[:errors] = ["Invalid Combination"]
    redirect_to :back
  end
end
def destroy
  reset_session
  redirect_to '/'
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home
  end

  def create
    @u = User.new(new_user)
    if @u.save
      session[:user_id] = @u.id
      redirect_to "/auctions"
    else
      flash[:errors] = @u.errors.full_messages
      redirect_to :back
    end
  end

  def subscribe
    @subscribe = Subscribe.new(:email => params[:email] )
    if @subscribe.save
      UserMailer.signup_confirmation(@subscribe).deliver_now
      redirect_to "/"
    else 
      redirect_to :back
    end
  end

  def new
  end

  def edit
    @user = User.find(session[:user_id])
    if @user.address_id != nil
      @address = Address.find(@user.address_id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(update_user)
      redirect_to :back
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to :back
    end
  end

  def destroy
  end
  private
    def new_user
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end

    def update_user
      params.require(:user).permit(:first_name, :last_name, :email, :company, :phone_number)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/auctions/edit.html.erb
<h1>Auctions#edit</h1>
<p>Find me in app/views/auctions/edit.html.erb</p>

app/views/auctions/index.html.erb
<div id="wrapper">
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class ="navbar-brand">
        <%=link_to( image_tag("logo.svg"), auctions_path) %>
      </div>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="/auctions" data-turbolinks="false">Home</a>
        </li>
        <% if @user.level >= 1 %>
          <% if @user.address_id != nil %>
          <li>
            <a href="/auctions/new">Add New Auction</a>
          </li>
          <li>
            <a href="/users/<%= @user.id %>/edit">Edit Profile</a>
          </li>
          <% end %>
        <% end %>
            <li>
              <a href="/sessions" data-method="delete">Logout</a>
            </li>
      </ul>
    </div>
  </div>
</div>
<br>
<br>
<br>
<div id="wrapper">

<div class="container">
  <div class="row">
    <div class="col align-self-center">
      <h3>Welcome, <%= @user.first_name %></h3>
      <h1>Active Auctions: (<%= @auctions.count %>)</h1>
      <br>
      <% if @user.level >= 1 %>
        <% if @user.address_id == nil %>
          <b>You have not added an address, you can add one <a href="/users/<%= @user.id %>/edit">here</a></b>
        <% end %>
      <% end %>
      <br>
      <br>
      <form>
        <div class="input-group">
          <form class="" action="index.html" method="post">
            <input type="text" class="form-control" name="search[search]" placeholder="Search Auctions" autofocus="true">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit">
                <i class="glyphicon glyphicon-search"></i>
              </button>
            </div>
          </form>
        </div>
        <table class="table table-hover">
        <thead>
          <tr>
            <td>Title</td>
            <td>Minimum Price</td>
            <td>Address</td>
            <td>End Date</td>
            <% if @user.level == 3 %>
            <td>Created By</td>
            <td>Actions</td>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <% @auctions.each do |auction| %>
          <tr>
            <td><%= auction.title %></td>
            <td>$ <%= auction.minimum_price %></td>
            <td><%= auction.address.street %> <%= auction.address.city %>, <%= auction.address.state %></td>
            <td><%= Time.diff(auction.auction_end + 7.days, Time.now ,'%d %hh %mm %ss')[:diff]%>
            </td>
                <% if @user.level == 3 %>
              <td><%= auction.user.first_name %> <%= auction.user.last_name %></td>
              <% end %>
            <td>
              <div class="dropdown">
                  <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Actions (<%= auction.id %>)
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                    <li><a href="/auctions/<%= auction.id %>" data-turbolinks="false">Bid</a></li>
                    <% if @user.level == 3 %>
                    <li><a href="/auctions/<%= auction.id %>" data-method="delete">Delete</a></li>
                    <% end %>
                  </ul>
                </div>
            </td>
            <% end %>
          </tr>
        </tbody>
      </table>
      </form>
      </div>
    </div>
  </div>
</div>

app/views/auctions/new.html.erb
<div id="wrapper">
<div class="navbar navbar-inverse navbar-fixed-top">
<div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class ="navbar-brand">
      <%=link_to( image_tag("logo.svg"), auctions_path) %>
    </div>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right">
      <li>
        <a href="/auctions" data-turbolinks="false">Home</a>
      </li>
      <li>
        <a href="/sessions" data-method="delete">Logout</a>
      </li>
    </ul>
  </div>
</div>
</div>
<br>
<br>
<br>
<div class="row">
  <div class="col-sm-8 diblock">
    <h1>Create New Auction</h1>
    <p>Address Information: </p>
    <%= @user.address.street %>
      <%= @user.address.city %>,
        <%= @user.address.state %>
          <%= @user.address.zip_code %>
            <br>
            <br>
            <form action="/auctions" method="post">
              <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"> Title:
              <input type="text" class="form-control" name="auction[title]" autofocus="true">
              <br> Description :
              <textarea class="form-control" name=auction[description]></textarea>
              <br> Minimum Price:
              <input type="number" name="auction[minimum_price]" class="form-control" step="any">
              <input type="hidden" name="auction[address_id]" value="<%= @user.address.id %>">
              <input type="hidden" name="auction[user_id]" value="<%= @user.id %>">
              <br>
              <button type="submit" class="btn btn-info">Create Auction</button>
            </form>
  </div>
  <div class="col-sm-4 diblock">
  <% if flash[:errors] %>
    <div class="diblock">
      <div class="col-sm">
        <% flash[:errors].each do |e| %>
          <div class="alert alert-danger">
            <strong>
              <%= e %>
            </strong>
          </div>
          <% end %>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/auctions/show.html.erb
<script src="//maps.google.com/maps/api/js?key="AIzaSyBvkzDkwN4uqroOeJitlDoGiRtHnD_7skk" "></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore.js"></script>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="container diblock">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class ="navbar-brand">
        <%=link_to( image_tag("logo.svg"), auctions_path) %>
      </div>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <a href="/auctions" data-turbolinks="false">Home</a>
        </li>
        <% if @user.level >= 1 %>
          <% if @user.address_id != nil %>
          <li>
            <a href="/auctions/new">Add New Auction</a>
          </li>
          <li>
            <a href="/users/<%= @user.id %>/edit">Edit Profile</a>
          </li>
          <% end %>
        <% end %>
            <li>
              <a href="/sessions" data-method="delete">Logout</a>
            </li>
      </ul>
    </div>
  </div>
</div>
<br>
<br>
<br>
<div id="wrapper">
<div class="container diblock">
  <div class="row diblock">
    <div class="col align-self-center">
<div class="panel panel-primary diblock background_1">
  <div class="panel-heading "><%= @auction_find.title %></div>
  <div class="panel-body"><br>
    <b>Description:</b>  <%= @auction_find.description %><br><br>
    <b>Temperature: </b> Dallas, TX: <b>71 F</b><br>
    <b>Number of Bids:</b> <%= @auction_find.bids.count %>
    <h2>Current Price
      <% if @auction_find.bids.empty? %>
        <%= @auction_find.minimum_price %>
      <% else %>
      $<%= @last_bid.price %>
      <% end %>
    </h2>
    <form action="/bids" method="post">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <input type="hidden" name="auction_id" value="<%= @auction_find.id %>">
        Bid <input type="number" step="any" class="form-control" name="price" style="width: 150px"><br /><button type="submit" class="btn btn-warning" style="display: inline-block">Bid! </button>
    </form><br><br>
    <% if @user.level > 1 %>
      Bid History <br><br><br>
      <% if @auction_history.empty? %>
      No Bids yet...
        <% else %>
        <% @auction_history.each do |history| %>
        User ID: <%= history.user_id %> bidded $<%=history.price %> on <%= history.created_at %> <br><hr>
        <% end %>
      <% end %>
      <% else %>
      <%end %>
    <h3><b>Past Auctions</b></h3>
    <table class = "table">
        <thead>
          <th>Title</th>
          <th>Description</th>
          <th>Minimum Price</th>
          <th>Auction Ended</th>
        </thead>
        <tbody>
        <% if @user.level == 0 %> 
            <% @pastauctions.each do |a| %>
            <tr>
              <td><%= a.title %></td>
              <td><%= a.description %></td>
              <td><%= a.minimum_price %></td>
              <td><%= a.auction_end %></td>
            </tr>
            <% end %>
        <% elsif @user.level == 1 %>
            <% @my_auctions.each do |m| %>
            <tr>
              <td><%= m.title %></td>
              <td><%= m.description %></td>
              <td><%= m.minimum_price %></td>
              <td><%= m.auction_end %></td>
            </tr>
            <% end %>
        <% elsif @user.level == 2 %>
            <% @all_auctions.each do |n| %>
            <tr>
                <td><%= n.title %></td>
                <td><%= n.description %></td>
                <td><%= n.minimum_price %></td>
                <td><%= n.auction_end %></td>
              </tr>
            <% end %>
        <% end %>
        </tbody>
      </table>

</div>
    </div>
  </div>
</div>
  <div class="row diblock">
    <div class="col align-self-right">
      <div style='width: 500px;' class="diblock">
        <div id="directions" style='width: 700px; height: 450px; margin-left: 250px;'></div>
      </div>
  </div>
</div>
</div>
</div>
<script type="text/javascript">
var directionsDisplay = new google.maps.DirectionsRenderer();
var directionsService = new google.maps.DirectionsService();

function calcRoute() {
  var origin      = new google.maps.LatLng(<%= @results.latitude %>, <%= @results.longitude %>);
  var destination = new google.maps.LatLng(32.777916, -96.803326);
  var request = {
      origin:      origin,
      destination: destination,
      travelMode:  google.maps.TravelMode.DRIVING
  };
  directionsService.route(request, function(response, status) {
    if (status == google.maps.DirectionsStatus.OK) {
      directionsDisplay.setDirections(response);
    }
  });
}

calcRoute();

var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'directions'}}, function(){
  directionsDisplay.setMap(handler.getMap());
});

</script>

app/views/dashboards/index.html.erb
<% if @user.level == 0 %>
<h2>Driver Dashboard</h2>
<% elsif @user.level == 1 %>
<h2>User Dashboard</h2>
<% elsif @user.level == 2 %>
<h2>Admin Dashboard</h2>
<% end %>
<h2>Recent Bids</h2>
<a href="/auctions">View All Auctions</a>
<table class="table">
  <thead>
    <tr>
      <td>Bid Date</td>
      <td>Bid Price</td>
      <td>Auction</td>
      <td>Status</td>
    </tr>
  </thead>
  <tbody>
    <% @bids.each do |bids| %>
    <tr>
      <td><%= bids.created_at%></td>
      <td>$<%= bids.price%></td>
      <td><a href="/auctions/<%= bids.auction.id%>"><%= bids.auction.title %></a></td>
      <td><%= bids.auction.status %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Logistics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900|Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/animate.css@3.5.2/animate.min.css">
  <link href="https://use.fontawesome.com/releases/v5.0.7/css/all.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

app/views/users/edit.html.erb
<div id="wrapper">
<div class="navbar navbar-inverse navbar-fixed-top">
<div class="container">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class ="navbar-brand">
      <%=link_to( image_tag("logo.svg"), auctions_path) %>
    </div>
  </div>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right">
      <li>
        <a href="/auctions" data-turbolinks="false">Home</a>
      </li>
        <% if @user.level >= 1 %>
          <% if @user.address_id != nil %>
            <li>
              <a href="/auctions/new">Add New Auction</a>
            </li>
          <% end %>
        <% end %>
      <li>
        <a href="/sessions" data-method="delete">Logout</a>
      </li>
    </ul>
  </div>
</div>
</div>
<br>
<br>
<br>

<div class="container">
    <h1>Edit Profile</h1>
  	<hr>
	<div class="row">

      <!-- edit form column -->
      <div class="col-md-12 personal-info diblock">
        <% if @user.level >= 1 %>
          <% if @user.address_id == nil %>
            <div class="alert alert-info alert-dismissable">
              <a class="panel-close close" data-dismiss="alert">×</a> 
              <i class="fa fa-map-marker"></i>
               You have not yet added an <strong>address</strong>. Please enter one below.
        </div>
          <% end %>
        <% end %>
        <div class="diblock col-md-8">
          <form class="form-horizontal" role="form" action="/users/<%= @user.id %>" method="post" >
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input name="_method" type="hidden" value="patch" />
            <div class="form-group">
              <label class="col-md-3 control-label">First name:</label>
              <div class="col-md-6">
                <input class="form-control" type="text" name="user[first_name]" value="<%= @user.first_name %>">
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">Last name:</label>
              <div class="col-md-6">
                <input class="form-control" type="text" name="user[last_name]" value="<%= @user.last_name %>">
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">Company:</label>
              <div class="col-md-6">
                <input class="form-control" type="text" name="user[company]" value="<%= @user.company %>">
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">Email:</label>
              <div class="col-md-6">
                <input class="form-control" type="text" name="user[email]" value="<%= @user.email %>">
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">Phone Number:</label>
              <div class="col-md-6">
                <input class="form-control" type="text" name="user[phone_number]" value="<%= @user.phone_number %>">
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label"></label>
              <div class="col-md-6">
                <input class="btn btn-primary" type="submit" value="UPDATE PROFILE">
              </div>
            </div>
        </form>
      </div>
      <% if flash[:errors] %>
        <div class="diblock mainbox col-md-4 col-sm-4">
          <div class="col-sm">
            <% flash[:errors].each do |e| %>
              <div class="alert alert-danger">
                <strong>
                  <%= e %>
                </strong>
              </div>
              <% end %>
          </div>
        </div>
      <% end %>      
      <div class="diblock col-md-8">
          <form class="form-horizontal" role="form" action="/addresses<% if @user.level >= 1 %><% if @user.address_id != nil %>/<%= @address.id %><% end %><% end%>" method="post" >
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <% if @user.level >= 1 %>
            <% if @user.address_id != nil %>            
            <input name="_method" type="hidden" value="patch" />
            <div class="form-group">
              <label class="col-md-3 control-label">Address:</label>
              <div class="col-md-6">
                <input class="form-control" type="text" name="address[street]" value="<%= @address.street %>">
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">City:</label>
              <div class="col-md-6">
                <input class="form-control" type="text" name="address[city]" value="<%= @address.city %>">
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">State:</label>
              <div class="col-md-6">
                <input class="form-control" type="text" name="address[state]" value="<%= @address.state %>">
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">Zip Code:</label>
              <div class="col-md-6">
                <input class="form-control" type="text" name="address[zip_code]" value="<%= @address.zip_code %>">
              </div>
            </div>
            <% else %>
            <div class="form-group">
              <label class="col-md-3 control-label">Address:</label>
              <div class="col-md-6">
                <input class="form-control" type="text" name="address[street]" value="">
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">City:</label>
              <div class="col-md-6">
                <input class="form-control" type="text" name="address[city]" value="">
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">State:</label>
              <div class="col-md-6">
                <input class="form-control" type="text" name="address[state]" value="">
              </div>
            </div>
            <div class="form-group">
              <label class="col-md-3 control-label">Zip Code:</label>
              <div class="col-md-6">
                <input class="form-control" type="number" name="address[zip_code]" value="">
              </div>
            </div>
            <% end %>
            <% end %>
            <div class="form-group">
              <label class="col-md-3 control-label"></label>
              <div class="col-md-6">
                <input class="btn btn-primary" type="submit" value="UPDATE ADDRESS">
              </div>
            </div>
        </form>
      </div>
      </div>
  </div>
</div>
<hr>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>